export enum Platform {
  FACEBOOK = 'FACEBOOK',
  LINKEDIN = 'LINKEDIN',
  SNAPCHAT = 'SNAPCHAT',
  INSTAGRAM = 'INSTAGRAM',
  THREADS = 'THREADS',
  TIKTOK = 'TIKTOK',
  GOOGLE = 'GOOGLE',
  PINTEREST = 'PINTEREST',
  CLAPPER = 'CLAPPER',
  YOUTUBE = 'YOUTUBE',
  TWITTER = 'TWITTER',
  BLUESKY = 'BLUESKY',
  TRUTH = 'TRUTH'
} 